import { imageSlots } from './imageSlots'

export type GuidedStepItem = {
  id: string
  stepNumber: number
  title: string
  subtitle?: string
  description: string
  bullets: string[]
  actionItems: string[]
  caution?: string
  imageSrc?: string
  imageAlt: string
  imageLabel: string
  imageNote?: string
  imagePlannedSrc?: string
  imageSourceRef?: string
  ctaLabel?: string
  ctaHref?: string
}

export const landingGuidedSteps: GuidedStepItem[] = [
  {
    id: 'landing-eligibility',
    stepNumber: 1,
    title: '먼저 지원 가능 여부부터 확인하세요',
    subtitle: '신청 전 자격 확인',
    description: '정상 영업 중인지, 지원 제외 사유가 없는지, 대표자 본인 명의로 진행 가능한지부터 확인하면 뒤 단계에서 덜 막힙니다.',
    bullets: ['정상 영업 여부 확인', '체납·지원 제외 사유 확인', '대표자 본인 명의 진행 가능 여부 확인'],
    actionItems: ['지금 할 일: 신청 자격 먼저 확인', '준비할 정보: 사업자 기본 정보와 대표자 명의 인증 수단', '확인할 점: 신청 주체가 대표자 본인인지 여부'],
    caution: '타인 명의 계정이나 정보로 진행하면 확인서 발급과 사업 신청 단계에서 다시 확인 요청이 올 수 있습니다.',
    imageSrc: imageSlots.landing.certificateJourney.src,
    imageAlt: imageSlots.landing.certificateJourney.alt,
    imageLabel: imageSlots.landing.certificateJourney.label,
    imageNote: imageSlots.landing.certificateJourney.note,
    imagePlannedSrc: imageSlots.landing.certificateJourney.plannedSrc,
    imageSourceRef: imageSlots.landing.certificateJourney.sourceRef,
    ctaLabel: '확인서 발급 가이드 보기',
    ctaHref: '/certificate-guide',
  },
  {
    id: 'landing-documents',
    stepNumber: 2,
    title: '자부담완화 해당 여부와 준비서류를 구분하세요',
    subtitle: '서류 준비',
    description: '일반지원 대상인지 자부담완화 대상인지 먼저 구분하면 어떤 증빙을 더 준비해야 하는지 한 번에 정리할 수 있습니다.',
    bullets: ['일반 50% / 자부담완화 60% 구분', '매장 사진, 동의 항목 준비', '추가 증빙서류 필요 여부 확인'],
    actionItems: ['지금 할 일: 필요한 서류 목록 정리', '준비할 정보: 사업자 정보, 자부담완화 증빙 가능 여부', '중요 체크: 자부담금과 부가세도 별도 준비'],
    caution: '자부담완화 관련 증빙은 공고 기준에 따라 달라질 수 있으므로 최종 제출 전 최신 공고문을 다시 확인해야 합니다.',
    imageSrc: imageSlots.certificateGuide.general[4].src,
    imageAlt: imageSlots.certificateGuide.general[4].alt,
    imageLabel: imageSlots.certificateGuide.general[4].label,
    imageNote: imageSlots.certificateGuide.general[4].note,
    imagePlannedSrc: imageSlots.certificateGuide.general[4].plannedSrc,
    imageSourceRef: imageSlots.certificateGuide.general[4].sourceRef,
  },
  {
    id: 'landing-certificate',
    stepNumber: 3,
    title: '소상공인 확인서를 단계대로 발급하세요',
    subtitle: '확인서 발급',
    description: '확인서 발급은 자료 제출, 신청서 작성, 진행상황 확인 순서로 진행하면 되고, 처음이면 단계별 화면을 보면서 따라가는 편이 가장 안전합니다.',
    bullets: ['발급 사이트 접속', '온라인 자료 제출 및 신청서 작성', '진행상황 확인 후 확인서 출력'],
    actionItems: ['지금 클릭할 메뉴: 소상공인 확인서 발급', '준비할 정보: 홈택스 연동 가능한 인증 수단과 기본 세무 자료', '확인할 점: 사업자 정보와 매출 정보 일치 여부'],
    caution: '매출액이나 업종 정보를 잘못 넣으면 확인서 결과가 달라질 수 있으니 제출 전에 숫자 단위와 표기를 다시 봐야 합니다.',
    imageSrc: imageSlots.certificateGuide.general[6].src,
    imageAlt: imageSlots.certificateGuide.general[6].alt,
    imageLabel: imageSlots.certificateGuide.general[6].label,
    imageNote: imageSlots.certificateGuide.general[6].note,
    imagePlannedSrc: imageSlots.certificateGuide.general[6].plannedSrc,
    imageSourceRef: imageSlots.certificateGuide.general[6].sourceRef,
    ctaLabel: '확인서 단계별 안내 열기',
    ctaHref: '/certificate-guide',
  },
  {
    id: 'landing-apply',
    stepNumber: 4,
    title: '스마트상점 사업 신청을 이어서 진행하세요',
    subtitle: '사업 신청',
    description: '확인서가 준비되면 스마트상점 사이트에서 공고를 선택하고, 희망 기술과 제품을 확인한 뒤 신청서를 작성해 제출합니다.',
    bullets: ['스마트상점 공고 진입', '희망 기술·모델 선택', '신청서 입력 및 서류 업로드'],
    actionItems: ['지금 클릭할 메뉴: 스마트상점 사업 신청 공고', '준비할 정보: 희망 모델, 활용 계획, 매장 관련 서류', '확인할 점: 최종 제출 전 첨부 파일 누락 여부'],
    caution: '최종 제출 후에는 수정이 번거로울 수 있으니 신청서 문장과 첨부 파일명을 마지막에 다시 확인하는 편이 좋습니다.',
    imageSrc: imageSlots.applyGuide.upload.src,
    imageAlt: imageSlots.applyGuide.upload.alt,
    imageLabel: imageSlots.applyGuide.upload.label,
    imageNote: imageSlots.applyGuide.upload.note,
    imagePlannedSrc: imageSlots.applyGuide.upload.plannedSrc,
    imageSourceRef: imageSlots.applyGuide.upload.sourceRef,
    ctaLabel: '사업 신청 단계별 안내 열기',
    ctaHref: '/smartstore-apply',
  },
  {
    id: 'landing-followup',
    stepNumber: 5,
    title: '제출 후 진행상황과 문의처를 바로 확인하세요',
    subtitle: '제출 이후',
    description: '접수 후에는 진행상황, 후속 일정, 지역 문의처를 바로 확인할 수 있어야 불필요한 대기를 줄일 수 있습니다.',
    bullets: ['접수 완료 여부 확인', '진행 일정 및 후속 절차 확인', '막히면 지역 문의처 또는 상담 이용'],
    actionItems: ['지금 할 일: 접수 완료 화면 저장', '준비할 정보: 접수 내역과 연락 가능한 전화번호', '확인할 점: 후속 연락이 오는 채널과 일정'],
    caution: '접수 완료 화면을 확인하지 않고 종료하면 제출 여부를 놓칠 수 있으니 마지막 화면을 꼭 저장하거나 캡처해 두는 편이 좋습니다.',
    imageSrc: imageSlots.applyGuide.timeline.src,
    imageAlt: imageSlots.applyGuide.timeline.alt,
    imageLabel: imageSlots.applyGuide.timeline.label,
    imageNote: imageSlots.applyGuide.timeline.note,
    imagePlannedSrc: imageSlots.applyGuide.timeline.plannedSrc,
    imageSourceRef: imageSlots.applyGuide.timeline.sourceRef,
    ctaLabel: '막히면 상담 신청하기',
    ctaHref: '#lead',
  },
]

export const certificateGeneralSteps: GuidedStepItem[] = [
  {
    id: 'general-login',
    stepNumber: 1,
    title: '발급 사이트에 접속하고 준비물을 확인하세요',
    subtitle: 'SMINFO 시작 단계',
    description: '먼저 대표자 본인 명의 인증 수단과 기본 신고 자료를 준비한 뒤 소상공인 확인서 발급 사이트에 접속합니다.',
    bullets: ['대표자 본인 인증 수단 준비', '최근 신고 자료 준비 여부 확인', '사이트 첫 화면에서 발급 메뉴 진입'],
    actionItems: ['지금 클릭할 메뉴: 소상공인 확인서 발급', '준비할 정보: 대표자 인증, 기본 세무 신고 자료', '먼저 할 일: 사이트 접속 후 발급 절차 시작'],
    caution: '홈택스 연동이 필요한 경우 대표자 본인 인증 상태가 아니면 다음 단계에서 막힐 수 있습니다.',
    imageSrc: imageSlots.certificateGuide.general[0].src,
    imageAlt: imageSlots.certificateGuide.general[0].alt,
    imageLabel: imageSlots.certificateGuide.general[0].label,
    imageNote: imageSlots.certificateGuide.general[0].note,
    imagePlannedSrc: imageSlots.certificateGuide.general[0].plannedSrc,
    imageSourceRef: imageSlots.certificateGuide.general[0].sourceRef,
    ctaLabel: '발급 사이트 바로가기',
    ctaHref: 'https://sminfo.mss.go.kr/',
  },
  {
    id: 'general-submit-docs',
    stepNumber: 2,
    title: '온라인 자료 제출 메뉴로 들어가세요',
    subtitle: '자료 제출 시작',
    description: '로그인 후 온라인 자료 제출 절차로 이동해 홈택스와 연동된 자료 제출을 시작합니다.',
    bullets: ['온라인 자료 제출 메뉴 선택', '안내 순서대로 동의 및 인증 진행', '자료 제출 화면 진입 확인'],
    actionItems: ['지금 클릭할 메뉴: 온라인 자료 제출', '준비할 정보: 홈택스 연동 가능한 인증 수단', '확인할 점: 최초 제출인지 여부'],
    caution: '처음 제출하는 경우 홈택스 인증 등록이 먼저 필요할 수 있습니다.',
    imageSrc: imageSlots.certificateGuide.general[1].src,
    imageAlt: imageSlots.certificateGuide.general[1].alt,
    imageLabel: imageSlots.certificateGuide.general[1].label,
    imageNote: imageSlots.certificateGuide.general[1].note,
    imagePlannedSrc: imageSlots.certificateGuide.general[1].plannedSrc,
    imageSourceRef: imageSlots.certificateGuide.general[1].sourceRef,
  },
  {
    id: 'general-business-info',
    stepNumber: 3,
    title: '사업자 정보와 제출 자료를 확인하세요',
    subtitle: '필수 정보 입력',
    description: '사업자 기본정보가 맞는지 확인하고 필요한 세무 자료가 빠짐없이 연결됐는지 검토합니다.',
    bullets: ['사업자등록번호와 상호 확인', '재무제표, 부가세, 원천세 자료 확인', '누락 자료가 없는지 점검'],
    actionItems: ['지금 클릭할 메뉴: 사업자 정보 확인', '준비할 정보: 재무제표, 부가세, 원천세 자료', '중요 체크: 업종과 사업자 정보 일치 여부'],
    caution: '사업자 정보가 실제 등록 정보와 다르면 심사 지연이 생길 수 있습니다.',
    imageSrc: imageSlots.certificateGuide.general[2].src,
    imageAlt: imageSlots.certificateGuide.general[2].alt,
    imageLabel: imageSlots.certificateGuide.general[2].label,
    imageNote: imageSlots.certificateGuide.general[2].note,
    imagePlannedSrc: imageSlots.certificateGuide.general[2].plannedSrc,
    imageSourceRef: imageSlots.certificateGuide.general[2].sourceRef,
  },
  {
    id: 'general-review-docs',
    stepNumber: 4,
    title: '제출한 자료가 정상인지 다시 확인하세요',
    subtitle: '조회 단계',
    description: '온라인으로 올린 자료가 모두 반영됐는지 조회 화면에서 하나씩 확인합니다.',
    bullets: ['제출 자료 조회 화면 확인', '각 항목 상태 정상 여부 점검', '누락 시 다시 제출 또는 보완'],
    actionItems: ['지금 클릭할 메뉴: 제출자료 조회', '준비할 정보: 제출한 자료 목록', '확인할 점: 정상 제출 표시 여부'],
    caution: '재무제표와 세무 자료가 일부만 반영되면 다음 신청 단계에서 오류가 날 수 있습니다.',
    imageSrc: imageSlots.certificateGuide.general[3].src,
    imageAlt: imageSlots.certificateGuide.general[3].alt,
    imageLabel: imageSlots.certificateGuide.general[3].label,
    imageNote: imageSlots.certificateGuide.general[3].note,
    imagePlannedSrc: imageSlots.certificateGuide.general[3].plannedSrc,
    imageSourceRef: imageSlots.certificateGuide.general[3].sourceRef,
  },
  {
    id: 'general-application',
    stepNumber: 5,
    title: '신청서를 차분히 작성하세요',
    subtitle: '기본정보 입력',
    description: '약관 동의 후 업종, 매출, 근로자 수 같은 기본 정보를 입력하고 신청서를 제출합니다.',
    bullets: ['약관 동의', '업종과 매출 정보 입력', '근로자 수 등 기본 정보 작성'],
    actionItems: ['지금 클릭할 메뉴: 신청서 작성', '준비할 정보: 업종, 매출액, 상시근로자 수', '입력 전 확인: 사업자등록일과 기본 정보'],
    caution: '사업자등록일이나 임원 수를 잘못 입력하면 재확인 요청이 올 수 있습니다.',
    imageSrc: imageSlots.certificateGuide.general[4].src,
    imageAlt: imageSlots.certificateGuide.general[4].alt,
    imageLabel: imageSlots.certificateGuide.general[4].label,
    imageNote: imageSlots.certificateGuide.general[4].note,
    imagePlannedSrc: imageSlots.certificateGuide.general[4].plannedSrc,
    imageSourceRef: imageSlots.certificateGuide.general[4].sourceRef,
  },
  {
    id: 'general-status',
    stepNumber: 6,
    title: '진행상황에서 결과를 확인하세요',
    subtitle: '심사 진행 확인',
    description: '신청서 제출 후에는 진행상황 메뉴에서 심사 상태와 보완 요청 여부를 확인할 수 있습니다.',
    bullets: ['진행상황 메뉴 진입', '심사 상태 확인', '보완 요청 여부 확인'],
    actionItems: ['지금 클릭할 메뉴: 진행상황 확인', '준비할 정보: 접수한 신청 내역', '확인할 점: 오류 또는 보완 요청 메시지'],
    caution: '유예검토 대상이면 추가 확인 절차가 이어질 수 있으니 안내 문구를 끝까지 확인하세요.',
    imageSrc: imageSlots.certificateGuide.general[5].src,
    imageAlt: imageSlots.certificateGuide.general[5].alt,
    imageLabel: imageSlots.certificateGuide.general[5].label,
    imageNote: imageSlots.certificateGuide.general[5].note,
    imagePlannedSrc: imageSlots.certificateGuide.general[5].plannedSrc,
    imageSourceRef: imageSlots.certificateGuide.general[5].sourceRef,
  },
  {
    id: 'general-print',
    stepNumber: 7,
    title: '확인서를 출력하고 다음 신청에 사용하세요',
    subtitle: '발급 완료',
    description: '발급이 완료되면 국문 확인서를 출력해 스마트상점 신청이나 보완서류 제출에 사용합니다.',
    bullets: ['발급된 확인서 선택', '국문 확인서 출력', '파일 저장 또는 인쇄'],
    actionItems: ['지금 클릭할 메뉴: 국문확인서 출력', '준비할 정보: 출력용 PC 또는 저장 위치', '마지막 확인: 기업명, 대표자명, 주소'],
    caution: '출력 전 표기 정보가 맞는지 꼭 확인하세요. 잘못된 정보는 다시 수정 요청이 필요할 수 있습니다.',
    imageSrc: imageSlots.certificateGuide.general[6].src,
    imageAlt: imageSlots.certificateGuide.general[6].alt,
    imageLabel: imageSlots.certificateGuide.general[6].label,
    imageNote: imageSlots.certificateGuide.general[6].note,
    imagePlannedSrc: imageSlots.certificateGuide.general[6].plannedSrc,
    imageSourceRef: imageSlots.certificateGuide.general[6].sourceRef,
    ctaLabel: '스마트상점 신청 가이드 보기',
    ctaHref: '/smartstore-apply',
  },
]

export const certificateStartupSteps: GuidedStepItem[] = [
  {
    id: 'startup-join',
    stepNumber: 1,
    title: '회원가입 후 약관에 동의하세요',
    subtitle: '창업 기업 시작 단계',
    description: '창업 기업은 온라인 자료 제출 없이 시작할 수 있으므로 회원가입과 약관 동의부터 진행하면 됩니다.',
    bullets: ['회원가입 또는 로그인', '약관 전체동의', '확인 버튼으로 다음 단계 이동'],
    actionItems: ['지금 클릭할 메뉴: 회원가입', '준비할 정보: 대표자 기본정보', '먼저 할 일: 약관 전체동의 체크'],
    caution: '창업 기업 절차인지 다시 확인한 뒤 진행하세요. 일반 사업자 절차와 입력 방식이 다를 수 있습니다.',
    imageSrc: imageSlots.certificateGuide.startup[0].src,
    imageAlt: imageSlots.certificateGuide.startup[0].alt,
    imageLabel: imageSlots.certificateGuide.startup[0].label,
    imageNote: imageSlots.certificateGuide.startup[0].note,
    imagePlannedSrc: imageSlots.certificateGuide.startup[0].plannedSrc,
    imageSourceRef: imageSlots.certificateGuide.startup[0].sourceRef,
    ctaLabel: '발급 사이트 바로가기',
    ctaHref: 'https://sminfo.mss.go.kr/',
  },
  {
    id: 'startup-form',
    stepNumber: 2,
    title: '신청서에 기본 정보를 입력하세요',
    subtitle: '신청서 작성',
    description: '본점사업자등록일, 업종, 매출액, 자산총액, 상시근로자 수를 입력하고 내용을 확인합니다.',
    bullets: ['사업자등록일 입력', '업종, 매출액, 자산총액 입력', '상시근로자 수 확인'],
    actionItems: ['지금 클릭할 메뉴: 신청서 작성', '준비할 정보: 사업자등록일, 매출액, 자산총액', '입력 전 확인: 숫자 단위와 한글 표기'],
    caution: '매출액 단위를 잘못 넣으면 결과가 다르게 나올 수 있으니 입력 후 한글 표기를 꼭 확인하세요.',
    imageSrc: imageSlots.certificateGuide.startup[1].src,
    imageAlt: imageSlots.certificateGuide.startup[1].alt,
    imageLabel: imageSlots.certificateGuide.startup[1].label,
    imageNote: imageSlots.certificateGuide.startup[1].note,
    imagePlannedSrc: imageSlots.certificateGuide.startup[1].plannedSrc,
    imageSourceRef: imageSlots.certificateGuide.startup[1].sourceRef,
  },
  {
    id: 'startup-print',
    stepNumber: 3,
    title: '제출 후 바로 결과를 확인하고 출력하세요',
    subtitle: '즉시 발급',
    description: '신청자 정보를 제출한 뒤 진행상황을 확인하고 소상공인 확인서를 바로 출력합니다.',
    bullets: ['신청자 정보 제출', '진행상황 확인', '확인서 즉시 출력'],
    actionItems: ['지금 클릭할 메뉴: 진행상황 확인', '준비할 정보: 신청 내역', '마지막 확인: 소기업(소상공인) 표기 여부'],
    caution: '중소기업 아님으로 보이면 매출액 입력 단위를 다시 확인하세요.',
    imageSrc: imageSlots.certificateGuide.startup[2].src,
    imageAlt: imageSlots.certificateGuide.startup[2].alt,
    imageLabel: imageSlots.certificateGuide.startup[2].label,
    imageNote: imageSlots.certificateGuide.startup[2].note,
    imagePlannedSrc: imageSlots.certificateGuide.startup[2].plannedSrc,
    imageSourceRef: imageSlots.certificateGuide.startup[2].sourceRef,
    ctaLabel: '스마트상점 신청 가이드 보기',
    ctaHref: '/smartstore-apply',
  },
]

export const smartStoreApplySteps: GuidedStepItem[] = [
  {
    id: 'apply-start',
    stepNumber: 1,
    title: '스마트상점 사이트에서 신청을 시작하세요',
    subtitle: '시작 위치 확인',
    description: '스마트상점 홈페이지에 접속한 뒤 대표자 본인 명의로 로그인하고 해당 공고에서 신청을 시작합니다.',
    bullets: ['스마트상점 사이트 접속', '대표자 본인 명의 로그인', '신청 공고 선택'],
    actionItems: ['지금 클릭할 메뉴: 사업 신청 공고', '준비할 정보: 대표자 계정', '먼저 할 일: 공고명과 지원 유형 확인'],
    caution: '대표자 본인 신청 원칙이므로 타인 계정으로 진행하면 접수에 문제가 생길 수 있습니다.',
    imageSrc: imageSlots.applyGuide.start.src,
    imageAlt: imageSlots.applyGuide.start.alt,
    imageLabel: imageSlots.applyGuide.start.label,
    imageNote: imageSlots.applyGuide.start.note,
    imagePlannedSrc: imageSlots.applyGuide.start.plannedSrc,
    imageSourceRef: imageSlots.applyGuide.start.sourceRef,
    ctaLabel: '스마트상점 신청 사이트 열기',
    ctaHref: 'https://www.sbiz.or.kr/smst/index.do',
  },
  {
    id: 'apply-menu',
    stepNumber: 2,
    title: '희망 기술과 제품 메뉴를 선택하세요',
    subtitle: '메뉴 선택',
    description: '공고 안에서 전자칠판 항목과 넥소 모델을 확인하고 희망 도입 순위를 선택합니다.',
    bullets: ['전자칠판 항목 선택', '넥소 모델 확인', '희망 도입 순위 입력'],
    actionItems: ['지금 클릭할 메뉴: 기술 선택', '준비할 정보: 희망 모델과 우선순위', '확인할 점: 선택한 모델명 일치 여부'],
    caution: '제품이나 기술 항목을 잘못 고르면 수정이 번거로우니 선택 화면에서 한 번 더 확인하세요.',
    imageSrc: imageSlots.applyGuide.menu.src,
    imageAlt: imageSlots.applyGuide.menu.alt,
    imageLabel: imageSlots.applyGuide.menu.label,
    imageNote: imageSlots.applyGuide.menu.note,
    imagePlannedSrc: imageSlots.applyGuide.menu.plannedSrc,
    imageSourceRef: imageSlots.applyGuide.menu.sourceRef,
  },
  {
    id: 'apply-form',
    stepNumber: 3,
    title: '신청서를 간단하고 정확하게 작성하세요',
    subtitle: '신청서 입력',
    description: '업체소개, 지원동기, 활용계획을 입력하고 필요한 첨부 서류를 준비해 최종 제출 단계로 넘어갑니다.',
    bullets: ['업체소개 입력', '지원동기와 활용계획 작성', '첨부 서류 준비 상태 점검'],
    actionItems: ['지금 클릭할 메뉴: 신청서 작성', '준비할 정보: 업체소개, 지원동기, 활용계획', '입력 전 확인: 매장 사진과 증빙 서류 준비 여부'],
    caution: '제출 후 수정이 어려울 수 있으니 문장과 첨부 파일을 제출 전에 다시 확인하세요.',
    imageSrc: imageSlots.applyGuide.upload.src,
    imageAlt: imageSlots.applyGuide.upload.alt,
    imageLabel: imageSlots.applyGuide.upload.label,
    imageNote: imageSlots.applyGuide.upload.note,
    imagePlannedSrc: imageSlots.applyGuide.upload.plannedSrc,
    imageSourceRef: imageSlots.applyGuide.upload.sourceRef,
  },
  {
    id: 'apply-finish',
    stepNumber: 4,
    title: '제출 후 진행상황을 확인하세요',
    subtitle: '제출 이후',
    description: '최종 제출이 끝나면 접수 여부와 이후 진행 일정을 확인하고, 안내에 맞춰 계약과 후속 절차를 준비합니다.',
    bullets: ['최종 제출 완료 확인', '진행상황 또는 일정 확인', '이후 계약 및 후속 절차 준비'],
    actionItems: ['지금 클릭할 메뉴: 진행상황 확인', '준비할 정보: 접수 내역과 연락 가능한 정보', '확인할 점: 제출 완료 표시와 후속 일정'],
    caution: '접수 완료 화면을 확인하지 않고 종료하면 제출 여부를 놓칠 수 있으니 마지막 확인이 필요합니다.',
    imageSrc: imageSlots.applyGuide.timeline.src,
    imageAlt: imageSlots.applyGuide.timeline.alt,
    imageLabel: imageSlots.applyGuide.timeline.label,
    imageNote: imageSlots.applyGuide.timeline.note,
    imagePlannedSrc: imageSlots.applyGuide.timeline.plannedSrc,
    imageSourceRef: imageSlots.applyGuide.timeline.sourceRef,
    ctaLabel: '확인서 발급 가이드 보기',
    ctaHref: '/certificate-guide',
  },
]
